services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    networks:
      - network
    env_file:
      - .env
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
    networks:
      - network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.0
    command: ["start-dev"]
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
    #healthcheck:
    #  test: [ "CMD-SHELL", "curl --head http://localhost:9000/health" ]
    #  interval: 10s
    #  timeout: 30s
    #  start_period: 30s
    #  retries: 3
    networks:
      - network
  notification-service:
    container_name: notification-service
    image: docker.io/library/notification-service:1.0.0
    networks:
      - network
    #depends_on:
    #  keycloak:
    #    condition: service_healthy
    env_file:
      - .env
  forum-service:
    container_name: forum-service
    image: docker.io/library/forum-service:1.0.0
    depends_on:
      - postgres
      - notification-service
    networks:
      - network
    env_file:
      - .env
  gateway:
    container_name: gateway
    image: docker.io/library/gateway:1.0.0
    ports:
      - "9090:8080"
    depends_on:
      - forum-service
    networks:
      - network

networks:
  network:
    name: forum-network
